api_platform:
    title: "Mon API"
    version: "1.0.0"

    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        html: ["text/html"]
        multipart: ["multipart/form-data"]

    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]

    patch_formats:
        json: ["application/merge-patch+json"]
